### ISSUE TITLE
Feature Columns to Preprocessing Layer

### ISSUE THREAD

**Issue by takumiohym** [GoogleCloudPlatform/asl-ml-immersion#194]
Following [the current recommendation](https://www.tensorflow.org/tutorials/structured_data/feature_columns) , refactor Feature Columns/DenseFeatures based codes to Preprocessing Layers

![image](https://user-images.githubusercontent.com/6895245/163512444-3ed8f68b-713a-423f-a643-47ca96a705c2.png)

## Environment
**Please test with Tensorflow>=v2.8.0**
Some labs are using [HashedCrossing](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/HashedCrossing?version=nightly) layer that was introduced in 2.8.0.

## Target Files (excluding non vertex labs)

introduction_to_tensorflow
- [ ] [2b_loading_filedata.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/8de323f806705e90f46c7e7225a87d013eaefde0/notebooks/introduction_to_tensorflow/solutions/2b_loading_filedata.ipynb)
- [x] [3_keras_sequential_api_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/8de323f806705e90f46c7e7225a87d013eaefde0/notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api.ipynb) -> #195
- [x] [4_keras_functional_api.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/introduction_to_tensorflow/solutions/3_keras_sequential_api_vertex.ipynb) -> #196

feature_engineering
- [ ] [3_keras_basic_feat_eng.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/1cde15b389189fc6ce5ab2414ced336ab022e7dd/notebooks/feature_engineering/solutions/3_keras_basic_feat_eng.ipynb)
- [x] [4_keras_adv_feat_eng.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/7115916cf40ae645bdabc9281bd7affd6711aefd/notebooks/feature_engineering/solutions/4_keras_adv_feat_eng.ipynb) -> #197

building_production_ml_systems 
- [x] [1_training_at_scale_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/c75c127e705278c0456b871004daafffe600ecc2/notebooks/building_production_ml_systems/solutions/1_training_at_scale_vertex.ipynb) -> #199
- [x] [2_hyperparameter_tuning_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/1b0225b16a5c4a846341e872b9c8b487b8231dc8/notebooks/building_production_ml_systems/solutions/2_hyperparameter_tuning_vertex.ipynb) -> #200
- [x] [4b_streaming_data_inference_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/1cde15b389189fc6ce5ab2414ced336ab022e7dd/notebooks/building_production_ml_systems/solutions/4b_streaming_data_inference_vertex.ipynb) -> #202 (Using this?)

end-to-end-structured
- [x] [4b_keras_dnn_babyweight.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/e6e38793960213211bbbfb03e06a373dd73c5fc3/notebooks/end-to-end-structured/labs/4b_keras_dnn_babyweight.ipynb) -> #204
- [x] [4c_keras_wide_and_deep_babyweight.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/e6e38793960213211bbbfb03e06a373dd73c5fc3/notebooks/end-to-end-structured/labs/4c_keras_wide_and_deep_babyweight.ipynb) -> #205
- [x] [5a_train_keras_ai_platform_babyweight_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/e6e38793960213211bbbfb03e06a373dd73c5fc3/notebooks/end-to-end-structured/solutions/5a_train_keras_ai_platform_babyweight_vertex.ipynb) and [5b_deploy_keras_ai_platform_babyweight_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/end-to-end-structured/solutions/5b_deploy_keras_ai_platform_babyweight_vertex.ipynb) -> #206

tfx_pipelines
- [ ] [walkthrough](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/notebooks/end-to-end-structured/solutions/5b_deploy_keras_ai_platform_babyweight_vertex.ipynb)
- [ ] [pipeline](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/master/notebooks/tfx_pipelines/pipeline)
- [ ] [cicd](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/master/notebooks/tfx_pipelines/cicd)
- [ ] [guided_project](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/master/notebooks/tfx_pipelines/guided_projects) (template itself is written in feature column?)

**Comment by sanjanalreddy** [comment]
@takumiohym regarding [2b_loading_filedata.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/8de323f806705e90f46c7e7225a87d013eaefde0/notebooks/introduction_to_tensorflow/solutions/2b_loading_filedata.ipynb) Let's update it too. We have not been using it in the virtual ASL but once in-person resumes, we might use it. 

And, regarding [3_keras_basic_feat_eng.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/1cde15b389189fc6ce5ab2414ced336ab022e7dd/notebooks/feature_engineering/solutions/3_keras_basic_feat_eng.ipynb) yes, I used it in my last cohort and we plan to use it in the next cohort.

**Comment by takumiohym** [comment]
OK thanks for your input!
I will add those next week.
